theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.5.5
  download_url: https://github.com/chrisant996/clink/releases/download/v1.5.5/clink.1.5.5.d4594d.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.5.5/clink.1.5.5.d4594d_setup.exe
