theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.5.8
  download_url: https://github.com/chrisant996/clink/releases/download/v1.5.8/clink.1.5.8.82f266.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.5.8/clink.1.5.8.82f266_setup.exe
