theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.5.7
  download_url: https://github.com/chrisant996/clink/releases/download/v1.5.7/clink.1.5.7.36d0c6.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.5.7/clink.1.5.7.36d0c6_setup.exe
