theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.6.10
  download_url: https://github.com/chrisant996/clink/releases/download/v1.6.10/clink.1.6.10.d5dce0.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.6.10/clink.1.6.10.d5dce0_setup.exe
