theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.6.3
  download_url: https://github.com/chrisant996/clink/releases/download/v1.6.3/clink.1.6.3.af47db.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.6.3/clink.1.6.3.af47db_setup.exe
