theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.5.16
  download_url: https://github.com/chrisant996/clink/releases/download/v1.5.16/clink.1.5.16.51802d.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.5.16/clink.1.5.16.51802d_setup.exe
