theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.6.12
  download_url: https://github.com/chrisant996/clink/releases/download/v1.6.12/clink.1.6.12.5cd618.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.6.12/clink.1.6.12.5cd618_setup.exe
