theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.5.15
  download_url: https://github.com/chrisant996/clink/releases/download/v1.5.15/clink.1.5.15.2528fa.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.5.15/clink.1.5.15.2528fa_setup.exe
