theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.6.20
  download_url: https://github.com/chrisant996/clink/releases/download/v1.6.20/clink.1.6.20.00f214.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.6.20/clink.1.6.20.00f214_setup.exe
