theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.6.2
  download_url: https://github.com/chrisant996/clink/releases/download/v1.6.2/clink.1.6.2.864f24.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.6.2/clink.1.6.2.864f24_setup.exe
