theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.5.14
  download_url: https://github.com/chrisant996/clink/releases/download/v1.5.14/clink.1.5.14.430a69.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.5.14/clink.1.5.14.430a69_setup.exe
