theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.5.11
  download_url: https://github.com/chrisant996/clink/releases/download/v1.5.11/clink.1.5.11.08c7e3.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.5.11/clink.1.5.11.08c7e3_setup.exe
