theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.5.4
  download_url: https://github.com/chrisant996/clink/releases/download/v1.5.4/clink.1.5.4.6f56dd.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.5.4/clink.1.5.4.6f56dd_setup.exe
