theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.6.13
  download_url: https://github.com/chrisant996/clink/releases/download/v1.6.13/clink.1.6.13.eb61b2.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.6.13/clink.1.6.13.eb61b2_setup.exe
