theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.5.9
  download_url: https://github.com/chrisant996/clink/releases/download/v1.5.9/clink.1.5.9.411d0f.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.5.9/clink.1.5.9.411d0f_setup.exe
