theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.6.11
  download_url: https://github.com/chrisant996/clink/releases/download/v1.6.11/clink.1.6.11.5e960c.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.6.11/clink.1.6.11.5e960c_setup.exe
