theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.6.8
  download_url: https://github.com/chrisant996/clink/releases/download/v1.6.8/clink.1.6.8.d61056.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.6.8/clink.1.6.8.d61056_setup.exe
