theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.5.18
  download_url: https://github.com/chrisant996/clink/releases/download/v1.5.18/clink.1.5.18.dd581e.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.5.18/clink.1.5.18.dd581e_setup.exe
