theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.6.7
  download_url: https://github.com/chrisant996/clink/releases/download/v1.6.7/clink.1.6.7.87398b.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.6.7/clink.1.6.7.87398b_setup.exe
