theme: jekyll-theme-cayman
title: Clink
github:
  version: v1.5.13
  download_url: https://github.com/chrisant996/clink/releases/download/v1.5.13/clink.1.5.13.290610.zip
  install_url:  https://github.com/chrisant996/clink/releases/download/v1.5.13/clink.1.5.13.290610_setup.exe
